
-- args to manually run this:
-- compile_test.lua
-- or if the cache file was created using debug_compile_test_create_cache.lua:
-- compile_test.lua -c temp/debug_test_filename_cache.lua

local arg_parser = require("lib.LuaArgParser.arg_parser")
local args_config = {
  options = {
    {
      field = "cache_filename",
      long = "cache-filename",
      short = "c",
      description = "Relative path to a cache file containing the list of files to compile",
      single_param = true,
      type = "string",
      optional = true,
    },
    {
      field = "test_disassembler",
      long = "test-disassembler",
      short = "d",
      description = "Ensure get_disassembly doesn't throw errors with freshly\n\z
        compiled data nor disassembled data. Also ensure disassembled\n\z
        and then dumped bytecode is the same as the original bytecode",
      flag = true,
    },
    {
      field = "ensure_clean_data",
      long = "ensure-clean",
      short = "e",
      description = "Ensure the compiler doesn't leave the ast in a modified state",
      flag = true,
    },
    {
      field = "test_formatter",
      long = "test-formatter",
      short = "r",
      description = "Ensure code => AST => code conversion preserves code structure",
      flag = true,
    },
    {
      field = "diff_files",
      long = "diff-files",
      short = "f",
      description = "Create files to be diffed for disassembler or compiler or generated bytecode issues\n\z
        Files would be at `E:/Temp/.Compare/temp1.txt` and `E:/Temp/.Compare/temp2.txt`",
      flag = true,
    },
  },
}

local args
do
  local err
  args, err = arg_parser.parse({...}, args_config)
  if (not args) or args.help then
    if not args then
      print(err)
      print()
    end
    print(arg_parser.get_help_string(args_config))
    return
  end
end

local phobos_env = {}
for k, v in pairs(_G) do
  phobos_env[k] = v
end
phobos_env.arg = nil

local compiled_modules
local cached_modules = {}
function phobos_env.require(module)
  if cached_modules[module] then
    return cached_modules[module]
  end
  local original_module = module
  if module:find("/") then
    if not module:find("%.lua$") then
      module = module..".lua"
    end
  else
    module = module:gsub("%.", "/")..".lua"
  end

  local chunk = assert(compiled_modules[module], "No module '"..module.."'.")
  local result = {chunk()}
  cached_modules[original_module] = result[1] == nil and true or result[1]
  return table.unpack(result)
end

local parser
local jump_linker
local fold_const
local phobos
local dump
local disassembler
local formatter

local compiled
local raw_compiled

local req

local function init()
  parser = req("parser")
  jump_linker = req("jump_linker")
  fold_const = req("optimize.fold_const")
  phobos = req("phobos")
  dump = req("dump")
  disassembler = req("disassembler")
  formatter = req("formatter")
end

local serpent = require("serpent")

local function compile(filename)
  local file = assert(io.open(filename,"r"))
  local text = file:read("*a")
  file:close()

  local ast = parser(text, "@"..filename)

  if args.test_formatter then
    local formatted = formatter(ast)
    if text ~= formatted then
      if args.diff_files then
        assert(io.open("E:/Temp/.Compare/temp1.txt", "w"))
          :write(text)
          :close()
        assert(io.open("E:/Temp/.Compare/temp2.txt", "w"))
          :write(formatted)
          :close()
      end
      error("Formatter has different output.")
    end
  end

  jump_linker(ast)
  fold_const(ast)
  local prev_ast_str
  if args.ensure_clean_data then
    prev_ast_str = serpent.block(ast)
  end
  local compiled_data = phobos(ast)

  if args.ensure_clean_data then
    local ast_str = serpent.block(ast)
    if ast_str ~= prev_ast_str then
      if args.diff_files then
        assert(io.open("E:/Temp/.Compare/temp1.txt", "w"))
          :write(prev_ast_str)
          :close()
        assert(io.open("E:/Temp/.Compare/temp2.txt", "w"))
          :write(ast_str)
          :close()
      end
      error("Compiler left a mess behind.")
    end
  end

  local bytecode = dump(compiled_data)

  if args.test_disassembler then
    local disassembled = disassembler.disassemble(bytecode)
    disassembler.get_disassembly(compiled_data, function() end, function() end)
    disassembler.get_disassembly(disassembled, function() end, function() end)
    if bytecode ~= dump(disassembled) then
      if args.diff_files then
        assert(io.open("E:/Temp/.Compare/temp1.txt", "w"))
          :write(serpent.block(compiled_data))
          :close()
        assert(io.open("E:/Temp/.Compare/temp2.txt", "w"))
          :write(serpent.block(disassembled))
          :close()
      end
      error("Disassembler has different output.")
    end
  end

  compiled[filename] = assert(load(bytecode, nil, "b", phobos_env))
  raw_compiled[filename] = bytecode
end

local function pcall_with_one_result(f, ...)
  local success, result = pcall(f, ...)
  if success then
    return result
  else
    return nil, result
  end
end

local filenames = {}
if args.cache_filename then
  filenames = assert(pcall_with_one_result(assert(loadfile(args.cache_filename, "t", {}))))
else
  filenames = require("debug_util").find_lua_source_files()
end

local function main()
  for _, filename in ipairs(filenames) do
    print(filename)
    compile(filename)
  end
end

print("compiling using phobos compiled by regular lua:")
local start_time = os.clock()

compiled = {}
raw_compiled = {}
req = require
init()
main()
local lua_result = compiled
local lua_raw_result = raw_compiled

print("compilation time ~ "..(os.clock() - start_time).."s")
print("--------")
print("compiling using phobos compiled by phobos:")
start_time = os.clock()

compiled_modules = lua_result
compiled = {}
raw_compiled = {}
req = phobos_env.require
init()
main()
local pho_result = compiled
local pho_raw_result = raw_compiled

print("compilation time ~ "..(os.clock() - start_time).."s")
print("--------")

local success = true
for k, v in pairs(pho_raw_result) do
  if v ~= lua_raw_result[k] then
    print("Bytecode differs for "..k..".")
    success = false
    if args.diff_files then
      assert(io.open("E:/Temp/.Compare/temp1.txt", "w"))
        :write(serpent.block(require("disassembler").disassemble(lua_raw_result[k])))
        :close()
      assert(io.open("E:/Temp/.Compare/temp2.txt", "w"))
        :write(serpent.block(require("disassembler").disassemble(v)))
        :close()
    end
  end
end

if success then
  print("No differences between compilation results - Success!")
end
